// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEb04GTaLApp_to6kxG2LC_S8U8CWHdhk',
    appId: '1:555605290126:web:8dc084d3caeea9b631eddf',
    messagingSenderId: '555605290126',
    projectId: 'blind-app-minchan',
    authDomain: 'blind-app-minchan.firebaseapp.com',
    storageBucket: 'blind-app-minchan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc1YRlRjPUmDCUuzwYvxmrQ-Gaob66lHM',
    appId: '1:555605290126:android:f86748e0be6a210031eddf',
    messagingSenderId: '555605290126',
    projectId: 'blind-app-minchan',
    storageBucket: 'blind-app-minchan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC89ELvaidOi_hV5I7h61e_HpQkVUUSZew',
    appId: '1:555605290126:ios:a179a4768508f10831eddf',
    messagingSenderId: '555605290126',
    projectId: 'blind-app-minchan',
    storageBucket: 'blind-app-minchan.firebasestorage.app',
    iosBundleId: 'com.minchan.blind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC89ELvaidOi_hV5I7h61e_HpQkVUUSZew',
    appId: '1:555605290126:ios:a179a4768508f10831eddf',
    messagingSenderId: '555605290126',
    projectId: 'blind-app-minchan',
    storageBucket: 'blind-app-minchan.firebasestorage.app',
    iosBundleId: 'com.minchan.blind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEb04GTaLApp_to6kxG2LC_S8U8CWHdhk',
    appId: '1:555605290126:web:73d2f16961682bdb31eddf',
    messagingSenderId: '555605290126',
    projectId: 'blind-app-minchan',
    authDomain: 'blind-app-minchan.firebaseapp.com',
    storageBucket: 'blind-app-minchan.firebasestorage.app',
  );
}
